apiVersion: v2
name: cert-manager
description: A Helm chart for Kubernetes
type: application
dependencies:
  - name: cert-manager
    version: &version v1.16.1
    repository: https://charts.jetstack.io
version: *version
