apiVersion: v2
name: argocd
description: A Helm chart for Kubernetes
type: application
dependencies:
  - name: argo-cd
    version: &version 6.11.1
    repository: https://argoproj.github.io/argo-helm
  - name: argocd-apps
    version: 1.4.1
    repository: https://argoproj.github.io/argo-helm
version: *version
