apiVersion: v2
name: argocd
description: A Helm chart for Kubernetes
type: application
dependencies:
  - name: argo-cd
    version: &version 5.51.4
    repository: https://argoproj.github.io/argo-helm
  - name: argocd-apps
    version: 1.6.2
    repository: https://argoproj.github.io/argo-helm
version: *version
