age:
  secretName: &ageSecretName helm-secrets-private-keys

argo-cd:
  global:
    image:
      repository: ghcr.io/kvanzuijlen/homelab/argoproj/argocd
  configs:
    cm:
      dex.config: |
        connectors:
          # GitHub example
          - type: github
            id: github
            name: GitHub
            config:
              clientID: $dex.github.clientID
              clientSecret: $dex.github.clientSecret
    repositories:
      argocd:
        name: argocd
        url: https://argoproj.github.io/argo-helm
        type: helm
      cert-manager:
        name: cert-manager
        url: https://charts.jetstack.io
        type: helm
      cloudflare:
        name: cloudflare
        url: https://cloudflare.github.io/helm-charts
        type: helm
      ingress-nginx:
        name: ingress-nginx
        url: https://kubernetes.github.io/ingress-nginx
        type: helm
      homelab:
        url: git@github.com:kvanzuijlen/homelab.git
        type: git
    credentialTemplates:
      homelab:
        url: git@github.com:kvanzuijlen/homelab.git
        type: git
    params:
      server.insecure: true
  applicationSet:
    enabled: false
  server:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/tls-acme: "true"
        "nginx.ingress.kubernetes.io/ssl-redirect": "false"
    config:
      helm.valuesFileSchemes: >-
        secrets,
        https
    rbacConfig:
      policy.default: role:readonly
      policy.csv: |
        g, kvanzuijlen, role:admin
  repoServer:
    env:
      - name: SOPS_AGE_KEY_FILE
        value: /helm-secrets-private-keys/key.txt
    volumes:
      - name: *ageSecretName
        secret:
          secretName: *ageSecretName
    volumeMounts:
      - mountPath: /helm-secrets-private-keys/
        name: *ageSecretName
    rbac:
      - apiGroups:
          - argoproj.io
        resources:
          - applications
        verbs:
          - get
          - list
          - watch
#argo-cd:
#  redis-ha:
#    enabled: true
#
#  controller:
#    replicas: 1
#
#  server:
#    autoscaling:
#      enabled: true
#      minReplicas: 2
#
#  repoServer:
#    autoscaling:
#      enabled: true
#      minReplicas: 2
#
#  applicationSet:
#    replicas: 2

argocd-apps:
  applications:
    - name: homelab-applications
      namespace: argocd
      project: homelab
      source:
        repoURL: git@github.com:kvanzuijlen/homelab.git
        targetRevision: HEAD
        path: helm/applications
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
  projects:
    - name: homelab
      namespace: argocd
      sourceRepos:
        - "*"
      destinations:
        - namespace: "*"
          server: https://kubernetes.default.svc
      clusterResourceWhitelist:
        - group: "*"
          kind: "*"
      orphanedResources:
        warn: false
