cloudflare-tunnel:
    cloudflare:
        account: ENC[AES256_GCM,data:WXEMWFC+czFPI6Z0XJJXf9JAYRhg8kYlCnI+OS+VOwY=,iv:/tTQo/t2JDWarTcbb6Ay+Mpx9uGRvec0KNzejznsZXI=,tag:y9ZSEM0f/YvhQBYAvgxNIA==,type:str]
        tunnelId: ENC[AES256_GCM,data:IKNdV8p/drZV55uZlB6ocLARxMBUN3mTH4uFUmz3xyxlC/gb,iv:SPDiLTAHv5K1S5zWT4ULdnYizi2pwDWiLoXNCgmLD4Y=,tag:G2Y2DSOY+MXvgVf1UKZ9tA==,type:str]
        secret: ENC[AES256_GCM,data:sXS4VB/90PKNtXylZBimMLVqozRgZZIhFGPhEJHD1ph0ZyhWw55JE055CfM=,iv:eQBgq3wi1esMcflMAAtHFqb1CNOxbjh4c34QzU6Wj58=,tag:rooE8jU001zTu3/oQidsSg==,type:str]
        ingress:
            - hostname: ENC[AES256_GCM,data:8SicgMaZ64p2BXLIdnoVQ5X4sgY=,iv:uGsNpjVres1QmxjSUUIWD7qJAX81A6YKBGHKDvVtdCE=,tag:ssX/3+Do+wicVAou303xuw==,type:str]
              service: ENC[AES256_GCM,data:FoXlLE2G+18uL64=,iv:WaHMoUKw0yfiuIJDHkMdQB1cEBQL9xfY5wusX9zccVY=,tag:Z9H/z85iQrct6icBMY9jUg==,type:str]
            - hostname: ENC[AES256_GCM,data:5qQ/NKPX3DG4LEYGmobA9A==,iv:x35nDWwsAXyhnz10dRWHscmxABwQGA4XQUKITnmGHRI=,tag:r1Lt5BGHW4sDoieSvX0VuQ==,type:str]
              service: ENC[AES256_GCM,data:g2Aa6Kqoiq+Ddab95cV5ATNtUa7u6GXa50qV3t2dmbpYae/QgaT1YNKvJqctqpxOrLFtns/AIqbEAtTrHfxH5Am1Xt8=,iv:KOC464VREgAhtoRCmHXgdv1Wjo412MeBWThMN2dst40=,tag:FOQ8//VSYgQKz0wMVfqtJA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cssrdxy259nz4k4fvqw6h08v54jvqf7gu7gxm0xp5t2tevp3d3wse9cmz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByT3Y4cWNwSndBRThJeWVB
            L1oyYVFhWnhxc3owRmpxcU5TcXgwZ1d6RGtVCm1lUUQzNlFSV3g4aVA5ZXZpZTJl
            eXRBbktMZVFVNWtrMG0ralZIOVlRb00KLS0tIGtBTGtSU0c1djYwMDhVVE5pRXRy
            YktBREp1WnRJTDJnQ0tLZEExQ09ZRjgKMyLKgwloWbwhqYfXavK/uwd8ZvpVzNJs
            6BfJLhG4O6JbDmi/4OkMhJlXpHRZytdjfl75ulbBoaDceP/ZUWU7fg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-26T16:35:23Z"
    mac: ENC[AES256_GCM,data:5KNmVH+8YESoZNMX8MbK32gOqlr2v9EBRMIMK5tXSKKRKggPXB6bxFYnkqk5dr429b1O6ofhpv0NK+gMb6E6p1RaSMpjhLQomSVB/fxMvguUvCl/oErWsCxTciz6kzxmNphGeijNT/tnsn/9k7nqo7Mgouk6TXO18+k2Mi3Rd0s=,iv:1OSllPG7NtfIs+DJDS7tCYGuYFMAMbTwmPpW7TFg86c=,tag:d/zWTMMupbg/fflE4/QMBw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
