apiVersion: v2
name: ingress-nginx
description: A Helm chart for Kubernetes
type: application
dependencies:
  - name: ingress-nginx
    version: &version 4.11.3
    repository: https://kubernetes.github.io/ingress-nginx
version: *version
